# brainrot_catalog.py
# Complete catalog of all Brainrot items in the Steal-a-Brainrot game.
# Sourced from the game's master configuration.
# Used for inventory checks, monitoring, and webhook alerts.

BRAINROT_CATALOG = [
    "Fortunu and Cashuru",
    "Los Amigos",
    "Los Sekolahs",
    "La Ginger Sekolah",
    "Sammyni Fattini",
    "Los Spaghettis",
    "Ventoliero Pavonero",
    "Cloverat Clapat",
    "Spaghetti Tualetti",
    "Rosetti Tualetti",
    "Duggy Bros",
    "Globa Steppa",
    "Fishino Clownino",
    "Gold Gold Gold",
    "Jolly Jolly Sahur",
    "Lavadorito Spinito",
    "Ketchuru and Musturu",
    "Tirilikalika Tirilikalako",
    "Swaggy Bros",
    "La Romantic Grande",
    "Orcaledon",
    "Tictac Sahur",
    "La Taco Combinasion",
    "Ketupat Kepat",
    "Dug dug dug",
    "Rico Dinero",
    "Tang Tang Keletang",
    "Lovin Rose",
    "Los Tacoritas",
    "Eviledon",
    "Los Primos",
    "W or L",
    "Esok Sekolah",
    "La Jolly Grande",
    "Los Cupids",
    "Los Puggies",
    "Tralaledon",
    "Gobblino Uniciclino",
    "Tuff Toucan",
    "Mieteteira Bicicleteira",
    "Chipso and Queso",
    "Chillin Chili",
    "Money Money Reindeer",
    "La Spooky Grande",
    "Bacuru and Egguru",
    "Los Bros",
    "La Extinct Grande",
    "Los Candies",
    "Los 67",
    "Celularcini Viciosini",
    "Los Mobilis",
    "Money Money Puggy",
    "Cigno Fulgoro",
    "Los Spooky Combinasionas",
    "Los Hotspotsitos",
    "Los Jolly Combinasionas",
    "Snailo Clovero",
    "Los Planitos",
    "Chicleteira Cupideira",
    "DJ Panda",
    "Las Sis",
    "Spinny Hammy",
    "Tacorita Bicicleta",
    "Los Sweethearts",
    "Nuclearo Dinossauro",
    "Chicleteira Noelteira",
    "Los Combinasionas",
    "Chimnino",
    "Noo my Gold",
    "Swag Soda",
    "Noo my Heart",
    "Tacorillo Crocodillo",
    "Mariachi Corazoni",
    "La Grande Combinasion",
    "Los 25",
    "Los Burritos",
    "67",
    "Donkeyturbo Express",
    "Los Chicleteiras",
    "Guest 666",
    "Los Mi Gatitos",
    "Rang Ring Bus",
    "Granny",
    "Noo my Present",
    "Serafinna Medusella",
    "Los Nooo My Hotspotsitos",
    "Arcadopus",
    "Noo my Candy",
    "Los Quesadillas",
    "Chicleteirina Bicicleteirina",
    "Chill Puppy",
    "Burrito Bandito",
    "Luck Luck Luck Sahur",
    "Chicleteira Bicicleteira",
    "Brunito Marsito",
    "Quesadillo Vampiro",
    "Eid Eid Eid Sahur",
    "Cupid Hotspot",
    "Mi Gatito",
    "Ho Ho Ho Sahur",
    "Cupid Cupid Sahur",
    "Pot Pumpkin",
    "Naughty Naughty",
    "Bunito Bunito Spinito",
    "Quesadilla Crocodila",
    "Horegini Boom",
    "Santa Hotspot",
    "Pot Hotspot",
    "25",
    "Pirulitoita Bicicleteira",
    "To to to Sahur",
    "Telemorte",
    "La Sahur Combinasion",
    "List List List Sahur",
    "Noo my examine",
    "Los Jobcitos",
    "Nooo My Hotspot",
    "Bunnyman",
    "Tung Tung Tung Sahur",
    "Cuadramat and Pakrahmatmamat",
    "Please my Present",
    "Los Cucarachas",
    "1x1x1x1",
    "La Vacca Lepre Lepreino",
    "Love Love Love Sahur",
    "Perrito Burrito",
    "Graipuss Medussi",
    "Giftini Spyderini",
    "GOAT",
    "Trickolino",
    "Paradiso Axolottino",
    "Triplito Tralaleritos",
    "La Vacca Jacko Linterino",
    "Fishboard",
    "Santteo",
    "Las Vaquitas Saturnitas",
    "Los Karkeritos",
    "Karker Sahur",
    "Los Trios",
    "Job Job Job Sahur",
    "Frankentteo",
    "Pumpkini Spyderini",
    "Las Tralaleritas",
    "Rocco Disco",
    "Extinct Matteo",
    "La Karkerkar Combinasion",
    "La Vacca Prese Presente",
    "Reindeer Tralala",
    "Yess my examine",
    "Guerriro Digitale",
    "Boatito Auratito",
    "Vulturino Skeletono",
    "Los Tralaleritos",
    "Zombie Tralala",
    "Los Tortus",
    "La Cucaracha",
    "Fragola La La La",
    "Extinct Tralalero",
    "Agarrini la Palini",
    "Los Spyderinis",
    "Chachechi",
    "Blackhole Goat",
    "Dul Dul Dul",
    "Torrtuginni Dragonfrutini",
    "Trenostruzzo Turbo 4000",
    "Karkerkar Kurkur",
    "Los Matteos",
    "Bisonte Giuppitere",
    "Sammyni Spyderini",
    "La Vacca Saturno Saturnita",
    "Jackorilla",
    "Digi Narwhal",
    "Bunny and Eggy",
    "Kalika Bros",
    "Cash or Card",
    "Los Chillis",
    "Hydra Bunny",
    "Boppin Bunny",
    "Gym Bros",
    "Quackini Snackini",
    "La Easter Grande",
    "Los Mariachis",
    "La Lucky Grande",
    "Churrito Bunnito",
    "Hopilikalika Hopilikalako",
    "Camera Ramena",
    "Baskito",
    "Bananito",
    "Noo my Eggs",
    "Strawberrita",
    "Los Bunitos",
    "Buho de Volto",
    "Bunny Bunny Bunny Sahur",
    "Berryno",
    "Easter Easter Easter Sahur",
    "Buntteo",
    "Secret Lucky Block",
    "Strawberry Elephant",
    "Meowl",
    "Headless Horseman",
    "Skibidi Toilet",
    "Griffin",
    "Hydra Dragon Cannelloni",
    "Dragon Gingerini",
    "Dragon Cannelloni",
    "La Supreme Combinasion",
    "Celestial Pegasus",
    "Cerberus",
    "Love Love Bear",
    "Popcuru and Fizzuru",
    "Rosey and Teddy",
    "Capitano Moby",
    "Cooki and Milki",
    "Burguro And Fryuro",
    "Ketupat Bros",
    "Reinito Sleighito",
    "La Secret Combinasion",
    "La Casa Boo",
    "Spooky and Pumpky",
    "Garama and Madundung",
    "Festive 67",
    "Ginger Gerat",
    "Nacho Spyder",
    "Antonio",
    "La Food Combinasion",
    "Fragrama and Chocrama",
    "Signore Carapace",
    "Elefanto Frigo",
]

# Categorized lists of brainrots
OG_ITEMS = [
    "Strawberry Elephant",
    "Meowl",
    "Headless Horseman",
    "Skibidi Toilet",
    "Griffin",
    "Hydra Dragon Cannelloni",
    "Dragon Gingerini",
    "Dragon Cannelloni",
    "La Supreme Combinasion",
    "Celestial Pegasus",
    "Cerberus",
    "Love Love Bear",
    "Popcuru and Fizzuru",
    "Rosey and Teddy",
    "Capitano Moby",
    "Cooki and Milki",
    "Burguro And Fryuro",
    "Ketupat Bros",
    "Reinito Sleighito",
    "La Secret Combinasion",
    "La Casa Boo",
    "Spooky and Pumpky",
    "Garama and Madundung",
    "Festive 67",
    "Ginger Gerat",
    "Nacho Spyder",
    "La Food Combinasion",
    "Fragrama and Chocrama",
    "Signore Carapace",
    "Elefanto Frigo",
]

ANTOH_ITEMS = [
    "Antonio",
]

# Mutually exclusive SECRET_ITEMS contains the remaining 197 items
SECRET_ITEMS = [item for item in BRAINROT_CATALOG if item not in OG_ITEMS and item not in ANTOH_ITEMS]

# Full overlapping secret list provided by user (excluding Antonio)
RAW_SECRET_LIST = [
    "Griffin", "Hydra Dragon Cannelloni", "Dragon Gingerini", "Dragon Cannelloni", "Love Love Bear",
    "La Supreme Combinasion", "Celestial Pegasus", "Cerberus", "Popcuru and Fizzuru", "Rosey and Teddy",
    "Capitano Moby", "Cooki and Milki", "Burguro And Fryuro", "Ketupat Bros", "Reinito Sleighito",
    "Fortunu and Cashuru", "Los Amigos", "La Secret Combinasion", "Los Sekolahs", "Signore Carapace",
    "La Casa Boo", "Fragrama and Chocrama", "La Food Combinasion", "Elefanto Frigo", "Spooky and Pumpky",
    "Ginger Gerat", "La Ginger Sekolah", "Sammyni Fattini", "Los Spaghettis", "Festive 67",
    "Ventoliero Pavonero", "Cloverat Clapat", "Spaghetti Tualetti", "Rosetti Tualetti",
    "Nacho Spyder", "Duggy Bros", "Globa Steppa", "Garama and Madundung", "Fishino Clownino",
    "Gold Gold Gold", "Jolly Jolly Sahur", "Lavadorito Spinito", "Ketchuru and Musturu",
    "Tirilikalika Tirilikalako", "Swaggy Bros", "La Romantic Grande", "Orcaledon", "Tictac Sahur",
    "La Taco Combinasion", "Ketupat Kepat", "Dug dug dug", "Rico Dinero", "Tang Tang Keletang",
    "Lovin Rose", "Los Tacoritas", "Eviledon", "Los Primos", "W or L", "Esok Sekolah",
    "La Jolly Grande", "Los Cupids", "Los Puggies", "Tralaledon", "Gobblino Uniciclino",
    "Tuff Toucan", "Mieteteira Bicicleteira", "Chipso and Queso", "Chillin Chili",
    "Money Money Reindeer", "La Spooky Grande", "Bacuru and Egguru", "Los Bros", "La Extinct Grande",
    "Los Candies", "Los 67", "Celularcini Viciosini", "Los Mobilis", "Money Money Puggy",
    "Cigno Fulgoro", "Los Spooky Combinasionas", "Los Hotspotsitos", "Los Jolly Combinasionas",
    "Snailo Clovero", "Los Planitos", "Chicleteira Cupideira", "DJ Panda", "Las Sis", "Spinny Hammy",
    "Tacorita Bicicleta", "Los Sweethearts", "Nuclearo Dinossauro", "Chicleteira Noelteira",
    "Los Combinasionas", "Chimnino", "Noo my Gold", "Swag Soda", "Noo my Heart",
    "Tacorillo Crocodillo", "Mariachi Corazoni", "La Grande Combinasion", "Los 25", "Los Burritos",
    "67", "Donkeyturbo Express", "Los Chicleteiras", "Guest 666", "Los Mi Gatitos",
    "Rang Ring Bus", "Granny", "Noo my Present", "Serafinna Medusella", "Los Nooo My Hotspotsitos",
    "Arcadopus", "Noo my Candy", "Los Quesadillas", "Chicleteirina Bicicleteirina", "Chill Puppy",
    "Burrito Bandito", "Luck Luck Luck Sahur", "Chicleteira Bicicleteira", "Brunito Marsito",
    "Quesadillo Vampiro", "Eid Eid Eid Sahur", "Cupid Hotspot", "Mi Gatito", "Ho Ho Ho Sahur",
    "Cupid Cupid Sahur", "Pot Pumpkin", "Naughty Naughty", "Bunito Bunito Spinito",
    "Quesadilla Crocodila", "Horegini Boom", "Santa Hotspot", "Pot Hotspot", "25",
    "Pirulitoita Bicicleteira", "To to to Sahur", "Telemorte", "La Sahur Combinasion",
    "List List List Sahur", "Noo my examine", "Los Jobcitos", "Nooo My Hotspot", "Bunnyman",
    "Tung Tung Tung Sahur", "Cuadramat and Pakrahmatmamat", "Please my Present", "Los Cucarachas",
    "1x1x1x1", "La Vacca Lepre Lepreino", "Love Love Love Sahur", "Perrito Burrito",
    "Graipuss Medussi", "Giftini Spyderini", "GOAT", "Trickolino", "Paradiso Axolottino",
    "Triplito Tralaleritos", "La Vacca Jacko Linterino", "Fishboard", "Santteo",
    "Las Vaquitas Saturnitas", "Los Karkeritos", "Karker Sahur", "Los Trios", "Job Job Job Sahur",
    "Frankentteo", "Pumpkini Spyderini", "Las Tralaleritas", "Rocco Disco", "Extinct Matteo",
    "La Karkerkar Combinasion", "La Vacca Prese Presente", "Reindeer Tralala", "Yess my examine",
    "Guerriro Digitale", "Boatito Auratito", "Vulturino Skeletono", "Los Tralaleritos",
    "Zombie Tralala", "Los Tortus", "La Cucaracha", "Fragola La La La", "Extinct Tralalero",
    "Agarrini la Palini", "Los Spyderinis", "Chachechi", "Blackhole Goat", "Dul Dul Dul",
    "Torrtuginni Dragonfrutini", "Trenostruzzo Turbo 4000", "Karkerkar Kurkur", "Los Matteos",
    "Bisonte Giuppitere", "Sammyni Spyderini", "La Vacca Saturno Saturnita", "Jackorilla",
    "Digi Narwhal", "Bunny and Eggy", "Kalika Bros", "Cash or Card", "Los Chillis",
    "Hydra Bunny", "Boppin Bunny", "Gym Bros", "Quackini Snackini", "La Easter Grande",
    "Los Mariachis", "La Lucky Grande", "Churrito Bunnito", "Hopilikalika Hopilikalako",
    "Camera Ramena", "Baskito", "Bananito", "Noo my Eggs", "Strawberrita", "Los Bunitos",
    "Buho de Volto", "Bunny Bunny Bunny Sahur", "Berryno", "Easter Easter Easter Sahur",
    "Buntteo", "Secret Lucky Block",
]

# Quick set lookups
BRAINROT_SET = set(BRAINROT_CATALOG)
OG_SET = set(OG_ITEMS)
SECRET_SET = set(SECRET_ITEMS)
ANTOH_SET = set(ANTOH_ITEMS)

def get_total_count():
    """Returns total number of brainrot items in the catalog."""
    return len(BRAINROT_CATALOG)

def is_valid_brainrot(name):
    """Checks if a given name matches a known brainrot item."""
    return name in BRAINROT_SET

def match_inventory(owned_list):
    """
    Given a list of item names a player owns, returns a dict with:
    - owned: list of valid brainrot names they own
    - missing: list of brainrot names they don't own
    - count_owned / count_missing / total
    - completion_pct: float 0-100
    """
    owned_set = set(owned_list) & BRAINROT_SET
    missing_set = BRAINROT_SET - owned_set
    total = len(BRAINROT_CATALOG)
    return {
        'owned': sorted(owned_set),
        'missing': sorted(missing_set),
        'count_owned': len(owned_set),
        'count_missing': len(missing_set),
        'total': total,
        'completion_pct': round((len(owned_set) / total) * 100, 2) if total else 0
    }
